In [1]:
from tqdm import tqdm
for i in tqdm(range(10)):
    print("tejas")

100%|██████████| 10/10 [00:00<00:00, 4940.87it/s]

tejas
tejas
tejas
tejas
tejas
tejas
tejas
tejas
tejas
tejas


In [2]:
from tqdm import tqdm
from time import sleep
for i in tqdm(range(100)):
    sleep(0.1)

100%|██████████| 100/100 [00:10<00:00,  9.56it/s]


In [6]:
from numpy import array, copy

In [7]:
x = array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
y =  x.copy()

In [9]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
x.fill(0)

In [11]:
x

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
z = x + y
z

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
zo = x + 1
zo

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
test_list = ['a', 'm', 'e', 'r', 'i', 'c', 'a', ]
test_list

['a', 'm', 'e', 'r', 'i', 'c', 'a']

In [20]:
dir(test_list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [21]:
test_list.__len__()

7

In [22]:
len(test_list)

7

In [23]:

# Python 3 code for printing 
# on the same line printing  
# geeks and geeksforgeeks  
# in the same line 
  
print("geeks", end =" ") 
print("geeksforgeeks") 

geeks geeksforgeeks


In [24]:
# array 
a = [1, 2, 3, 4] 
  
# printing a element in same 
# line 
for i in range(4): 
    print(a[i], end =" ")  

1 2 3 4 

In [ ]:
for i in range(len(test_list)):
    if i - 1 = 3 :
        print("000000", end = "" )
    else :
        print(" ")
    print(test_list[i])
