# Imports

In [71]:
# # Imports

# ## Qutip imports 1

# In[1]:


from qutip.operators import sigmax, sigmay, sigmaz, identity, qeye
from qutip.operators import position, momentum, num, create, destroy
from qutip.operators import commutator, qdiags
from qutip.simdiag import simdiag
from qutip.states import basis, ket2dm
from qutip.tensor import tensor
from qutip.qip.gates import swap, rx, ry, rz, cnot
from qutip.qobj import Qobj
from qutip.visualization import hinton
from qutip.visualization import matrix_histogram_complex, matrix_histogram
from qutip.random_objects import rand_herm, rand_unitary, rand_dm


# ## Qutip imports 2

# In[3]:


#from 


# ## Numpy imports 

# In[2]:


from numpy import sin, cos, tan, real, imag,  log, conj
from numpy import array, append, linspace, arange
from numpy import add, sqrt, abs, dot
from numpy.random import random, random_sample, rand, seed, RandomState
from numpy import concatenate, hstack, vstack, block, dstack, vsplit
from numpy import trace, diag
from numpy import ones, zeros, ones_like, zeros_like
from numpy import amax, amin, nanmax, nanmin
from numpy import outer, multiply
# from numpy import pi


# ## Scipy imports

# In[17]:


from scipy.integrate import ode, odeint, complex_ode
from scipy.optimize import minimize
from scipy.linalg import eigh, inv, norm, expm
# from scipy.linalg import 
# from scipy import


# ## Matplotlib imports

# In[18]:


from matplotlib.pyplot import plot, figure, show, savefig, axes
from matplotlib.pyplot import xlabel, ylabel, title, legend
from matplotlib import rcParams
from matplotlib.pyplot import style 
from matplotlib.pyplot import xlim, ylim, axis 
# beware not same as axes
from matplotlib.pyplot import subplot, subplots, text
from matplotlib.pyplot import GridSpec
from matplotlib.pyplot import scatter, colorbar


pgf_with_rc_fonts = {"pgf.texsystem": "pdflatex"}
rcParams.update(pgf_with_rc_fonts)
style.use('seaborn-whitegrid')


# ## Math imports

# In[19]:


from math import pi
from math import exp


# ## Cmath imports

# ## Date and datetime imports

# In[20]:


from datetime import date
from datetime import datetime# now


# ## Os imports

# In[21]:


from os import getcwd, mkdir, chdir
from os.path import abspath, join 


# ## Sympy imports

# In[22]:


from sympy import Function, dsolve, Eq, Derivative, symbols
# x, y, z, t = symbols('x y z t')
# k, m, n = symbols('k m n', integer=True)
# f, g, h = symbols('f g h', cls=Function)


# ## Miscellaneous imports

# ## Extra useful functions

# In[23]:


def rint(x):
    print("x = ", x)
    return None


# # Next chapter

# ## sub topic 1

# ## sub topic 2

# ## sub topic 3

# ### sub sub topic 1



# Next chapter

## memory clear (uses regex, so be careful)

In [30]:
%reset_selective -f var1, var2  # replace var1, var2 with your defined ones

## sub topic 2

In [31]:
cnot()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [32]:
(qeye(2)- sigmaz())/2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]]

In [33]:
(-qeye(2) + sigmax())

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[-1.  1.]
 [ 1. -1.]]

In [34]:
tensor((qeye(2)- sigmaz())/2,(-qeye(2) + sigmax())          )

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -1.  1.]
 [ 0.  0.  1. -1.]]

In [35]:
(1j*(pi/4)*tensor((qeye(2)- sigmaz())/2,(-qeye(2) + sigmax())          )).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1. +0.j  0. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  1. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  0. +0.j  0.5-0.5j 0.5+0.5j]
 [0. +0.j  0. +0.j  0.5+0.5j 0.5-0.5j]]

In [10]:
(1*(pi/4)*tensor((qeye(2)- sigmaz())/2,(-qeye(2) + sigmax())          )).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         0.60393979 0.39606021]
 [0.         0.         0.39606021 0.60393979]]

In [12]:
(1j*(pi/4)*(1j)*tensor((qeye(2)- sigmaz())/2,(-qeye(2) + sigmax())  )).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          2.90523869 -1.90523869]
 [ 0.          0.         -1.90523869  2.90523869]]

## sub topic 3

### sub sub topic 1

In [13]:
cnot()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [14]:
cnot().eigenenergies()

array([-1.,  1.,  1.,  1.])

In [15]:
cnot().eigenstates()

(array([-1.,  1.,  1.,  1.]),
 array([Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[ 0.        ]
  [ 0.        ]
  [ 0.70710678]
  [-0.70710678]],
        Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[0.]
  [1.]
  [0.]
  [0.]],
        Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[1.]
  [0.]
  [0.]
  [0.]],
        Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[0.        ]
  [0.        ]
  [0.70710678]
  [0.70710678]]], dtype=object))

In [16]:
cnot().diag()

array([1., 1., 0., 0.])

In [20]:
c_eigenvalue, c_eigenvec_arr = cnot().eigenstates()


In [23]:
c_eigenvec

array([Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.        ]
 [ 0.70710678]
 [-0.70710678]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [0.70710678]
 [0.70710678]]], dtype=object)

In [24]:
c_eigenvalue

array([-1.,  1.,  1.,  1.])

In [27]:
qdiags(2)

TypeError: qdiags() missing 1 required positional argument: 'offsets'

In [37]:
simdiag(array([sigmax(), qeye(2)]))

AttributeError: 'zip' object has no attribute 'sort'

In [26]:
d = qdiags(c_eigenvalue)
d

TypeError: qdiags() missing 1 required positional argument: 'offsets'

In [38]:
Qobj(diag(c_eigenvalue.full()))

AttributeError: 'numpy.ndarray' object has no attribute 'full'

In [40]:
ceq = Qobj(diag(c_eigenvalue))
ceq

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

In [42]:
Qobj(arange(9).reshape((3,3)))

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

In [44]:
inter = [a.full() for a in c_eigenvec] 

In [45]:
inter

[array([[ 0.        +0.j],
        [ 0.        +0.j],
        [ 0.70710678+0.j],
        [-0.70710678+0.j]]), array([[0.+0.j],
        [1.+0.j],
        [0.+0.j],
        [0.+0.j]]), array([[1.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j]]), array([[0.        +0.j],
        [0.        +0.j],
        [0.70710678+0.j],
        [0.70710678+0.j]])]

In [46]:
array(c_eigenvec)

array([Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.        ]
 [ 0.70710678]
 [-0.70710678]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [0.70710678]
 [0.70710678]]], dtype=object)

In [47]:
array(inter)

array([[[ 0.        +0.j],
        [ 0.        +0.j],
        [ 0.70710678+0.j],
        [-0.70710678+0.j]],

       [[ 0.        +0.j],
        [ 1.        +0.j],
        [ 0.        +0.j],
        [ 0.        +0.j]],

       [[ 1.        +0.j],
        [ 0.        +0.j],
        [ 0.        +0.j],
        [ 0.        +0.j]],

       [[ 0.        +0.j],
        [ 0.        +0.j],
        [ 0.70710678+0.j],
        [ 0.70710678+0.j]]])

In [48]:
crq = Qobj(array(inter))
crq

TypeError: expected dimension <= 2 array or matrix

In [55]:
crq = Qobj(block([inter[0], inter[1], inter[2], inter[3]]))

In [56]:
crq

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.          0.          1.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.70710678  0.          0.          0.70710678]
 [-0.70710678  0.          0.          0.70710678]]

In [57]:
ceq

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

In [58]:
crq*ceq*(crq.dag())

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [60]:
cnot()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [59]:
(crq.dag())*ceq*crq

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]

In [62]:
α = tensor(sigmax(), sigmax()) + tensor(sigmay(), sigmay())
α

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 2. 0.]
 [0. 2. 0. 0.]
 [0. 0. 0. 0.]]

In [63]:
(-1j*(1/8)*α).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.96891242+0.j         0.        -0.24740396j
  0.        +0.j        ]
 [0.        +0.j         0.        -0.24740396j 0.96891242+0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  1.        +0.j        ]]

In [64]:
(1j*(1/8)*α).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.96891242+0.j         0.        +0.24740396j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.24740396j 0.96891242+0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  1.        +0.j        ]]

In [65]:
(1j*(1/4)*α).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.87758256+0.j         0.        +0.47942554j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.47942554j 0.87758256+0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  1.        +0.j        ]]

In [66]:
(1j*(pi/4)*α).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]

In [67]:
(-1j*(pi/8)*α).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.70710678+0.j         0.        -0.70710678j
  0.        +0.j        ]
 [0.        +0.j         0.        -0.70710678j 0.70710678+0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  1.        +0.j        ]]

In [69]:
β = tensor(sigmax(), sigmax())
β

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

In [70]:
(1j*(pi/4)*β).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.70710678+0.j         0.        +0.j         0.        +0.j
  0.        +0.70710678j]
 [0.        +0.j         0.70710678+0.j         0.        +0.70710678j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.70710678j 0.70710678+0.j
  0.        +0.j        ]
 [0.        +0.70710678j 0.        +0.j         0.        +0.j
  0.70710678+0.j        ]]

In [75]:
one = basis(2,0)
one

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [76]:
zero = basis(2,1)
zero

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [78]:
aas = (1/sqrt(2))*(tensor(one, zero) + 1j*tensor(zero, one))

In [79]:
aas

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.70710678j]
 [0.        +0.j        ]]

In [80]:
ket2dm(aas)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. +0.j  0. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  0.5+0.j  0. -0.5j 0. +0.j ]
 [0. +0.j  0. +0.5j 0.5+0.j  0. +0.j ]
 [0. +0.j  0. +0.j  0. +0.j  0. +0.j ]]

In [70]:
(1j*(pi/4)*β).expm()*

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.70710678+0.j         0.        +0.j         0.        +0.j
  0.        +0.70710678j]
 [0.        +0.j         0.70710678+0.j         0.        +0.70710678j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.70710678j 0.70710678+0.j
  0.        +0.j        ]
 [0.        +0.70710678j 0.        +0.j         0.        +0.j
  0.70710678+0.j        ]]

In [ ]:
#g = pi/(4 * T) T = 2 * np.pi 
#H = g * (tensor(sigmax(), sigmax()) + tensor(sigmay(), sigmay()))

In [84]:
H = (1/(4 * 2 ))* (tensor(sigmax(), sigmax()) + tensor(sigmay(), sigmay()))

In [85]:
(-1j*H*2*pi).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]

In [86]:
(1j*H*2*pi).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]

In [87]:
(H*2*pi).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1.         0.         0.         0.        ]
 [0.         2.50917848 2.3012989  0.        ]
 [0.         2.3012989  2.50917848 0.        ]
 [0.         0.         0.         1.        ]]