# Imports

## Qutip imports 1

In [1]:
from qutip.operators import sigmax, sigmay, sigmaz, identity
# position, momentum, num, create, destroy, commutator, qeye 
from qutip.tensor import tensor
from qutip.qip.gates import swap, rx, ry, rz
from qutip.qobj import Qobj
from qutip.visualization import hinton
from qutip.visualization import matrix_histogram_complex, matrix_histogram
from qutip.random_objects import rand_herm, rand_unitary, rand_dm



## Numpy imports 

In [6]:
from numpy import sin, cos, tan, real, imag,  log, conj
from numpy import array, append, linspace, arange
from numpy import add, sqrt, abs, dot
from numpy.random import random, random_sample, random
from numpy import concatenate, trace
from numpy import ones, zeros, ones_like, zeros_like
from numpy import amax, amin, nanmax, nanmin
# from numpy import pi




## Scipy imports

In [7]:
from scipy.integrate import ode, odeint, complex_ode
from scipy.optimize import minimize
from scipy.linalg import eigh, inv, norm, expm
# from scipy.linalg import 
# from scipy import

## Matplotlib imports

In [8]:
from matplotlib.pyplot import plot, figure, show, savefig, axes
from matplotlib.pyplot import xlabel, ylabel, title, legend
from matplotlib import rcParams
from matplotlib.pyplot import style 
from matplotlib.pyplot import xlim, ylim, axis 
# beware not same as axes
from matplotlib.pyplot import subplot, subplots, text
from matplotlib.pyplot import GridSpec



pgf_with_rc_fonts = {"pgf.texsystem": "pdflatex"}
rcParams.update(pgf_with_rc_fonts)
style.use('seaborn-whitegrid')



## Math imports

In [9]:
from math import pi
from math import exp

## Cmath imports

## Date and datetime imports

In [10]:
from datetime import date
from datetime import datetime# now


## Os imports

In [11]:
from os import getcwd, mkdir, chdir
from os.path import abspath, join 


## Sympy imports

In [12]:
from sympy import Function, dsolve, Eq, Derivative, symbols
# x, y, z, t = symbols('x y z t')
# k, m, n = symbols('k m n', integer=True)
# f, g, h = symbols('f g h', cls=Function)

## Miscellaneous imports

## Extra useful functions

In [13]:
def rint(x):
    print("x = ", x)
    return None

# Building parts

In [14]:
 del omega_1, total_time, epsilon, 
omega_1 = 0.5
total_time = 2*pi/omega_1
epsilon = 10**(-6)
max_iter = 100
time_steps = 200
dt = total_time/time_steps

NameError: name 'omega_1' is not defined

In [15]:
del Lin, Ti

NameError: name 'Lin' is not defined

In [16]:
Lin

NameError: name 'Lin' is not defined

## level 1

In [17]:
def H1(omega_1):
    r"""Brief description of the function"""
    H1 = omega_1*sigmaz()
    return H1


In [18]:
def H2():
    r"""Brief description of the function"""
    H2 = sigmay()
    return H2

In [19]:
#I = identity(2)
del I

NameError: name 'I' is not defined

In [20]:
def T_maker(Ti):
    r"""Brief description of the function"""
    T = tensor(Ti.trans(), Ti)
    return T

In [21]:
 tensor(identity(2), T_maker(sigmax()))

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]

## level 2

In [22]:
def Hamil(omega_1, xi):
    H = H1(omega_1) + xi*H2()
    return H

In [23]:
Hamil(2, 0.5 )

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 2.+0.j   0.-0.5j]
 [ 0.+0.5j -2.+0.j ]]

In [24]:
def leftover(Lin):
    r"""Brief description of the function"""
    d = Lin.shape[0]
    I = identity(d)
    term1 = tensor(Lin.trans(), Lin)
    term2 = tensor(I, ((Lin.dag())*(Lin)))
    term3 = tensor(((Lin.trans())*(Lin.conj())), I)
    leftover = 1j*(0.1)*(term1 - 0.5*(term2 + term3))
    return leftover


def A(omega_1, xi, Lin):
    H = Hamil(omega_1, xi)
    d = Lin.shape[0]
    I = identity(d)
    A = tensor(I, H) - tensor((H.conj()), I) + leftover(Lin)
    return A

In [25]:
A(2, 0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.+0.j   0.-0.5j  0.-0.5j  0.+0.j ]
 [ 0.+0.5j -4.-0.2j  0.+0.j   0.-0.5j]
 [ 0.+0.5j  0.+0.j   4.-0.2j  0.-0.5j]
 [ 0.+0.j   0.+0.5j  0.+0.5j  0.+0.j ]]

In [26]:
A(0, 0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.+0.j  0.-0.5j 0.-0.5j 0.+0.j ]
 [0.+0.5j 0.-0.2j 0.+0.j  0.-0.5j]
 [0.+0.5j 0.+0.j  0.-0.2j 0.-0.5j]
 [0.+0.j  0.+0.5j 0.+0.5j 0.+0.j ]]

In [27]:
I

NameError: name 'I' is not defined

In [28]:
#term1 = tensor(Lin.trans(), Lin)
#term2 = tensor(I, ((Lin.dag())*(Lin)))
#term3 = tensor(((Lin.trans())*(Lin.conj())), I)
#leftover = 1j*(0.1)*(term1 - 0.5*(term2 + term2))
def x_k(omega_1, Lin ):
    r"""Brief description of the function"""
    #H11 = H1(omega_1)
    #H2_i = H2()
    d = Lin.shape[0]
    I = identity(d)
    x_k = tensor(I, H2()) - tensor((H2().conj()), I) #+ leftover(Lin)
    return x_k


In [29]:
I

NameError: name 'I' is not defined

In [30]:
x_k(0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j 0.-1.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+1.j 0.+1.j 0.+0.j]]

In [31]:
def L(omega_1, xi, Lin, dt):
    #H = H1
    L = (-1j*A(omega_1, xi, Lin)*dt).expm()
    return L

In [32]:
L(0.5, 2, sigmaz(), 0.001)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 9.99996000e-01+0.00000000e+00j -1.99979435e-03-9.99865260e-07j
  -1.99979435e-03+9.99865260e-07j  3.99972768e-06+0.00000000e+00j]
 [ 1.99979435e-03+9.99865260e-07j  9.99795521e-01+9.99797187e-04j
  -3.99946104e-06+0.00000000e+00j -1.99979435e-03-9.99865260e-07j]
 [ 1.99979435e-03-9.99865260e-07j -3.99946104e-06+0.00000000e+00j
   9.99795521e-01-9.99797187e-04j -1.99979435e-03+9.99865260e-07j]
 [ 3.99972768e-06+0.00000000e+00j  1.99979435e-03+9.99865260e-07j
   1.99979435e-03-9.99865260e-07j  9.99996000e-01+0.00000000e+00j]]

In [33]:
def L_I(Ti):
    r"""Brief description of the function"""
    d = Ti.shape[0]
    I = identity(d)
    L_I = tensor(I, I)
    return L_I

In [34]:
L_I(sigmay())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

## parameters

### sub sub topic 1

In [35]:
# building the function to optimize (optimizee)
def L_vec(omega_1, xi_vec, Lin, dt):
    #xi_vec_size = 2#xi_vec.size # finding the size of xi
    L_vec = [L(omega_1, xi, Lin, dt) for xi in xi_vec] 
    # constructing L #[L(1.0), L(2.0)]
    
    return L_vec


In [36]:
def fidelity_calc(A, B):
    r"""Brief description of the function"""
    d1 = A.shape[0] # Assuming no rectangular shaped matrices
    d2 = B.shape[0] # Assuming no rectangular shaped matrices
    d = d1*d2
    first_part = (A - B).dag()
    second_part = (A - B)
    f_int = (first_part* second_part)
    f = f_int.tr()
    return f

In [37]:
def L_full_maker(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    xi_vec_size = xi_vec.size # finding the size of xi
    L_full = L_I(Ti) # Identity for the for loop of L
    L_v = L_vec(omega_1, xi_vec, Lin, dt) # calling L_vec
    for i in range(xi_vec_size): # generating L_full
        L_full = L_full*L_v[xi_vec_size - 1 - i]
    return L_full

In [38]:
def F(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    L_full = L_full_maker(Ti, omega_1, xi_vec, Lin, dt)
    T = T_maker(Ti)
    F = real(-fidelity_calc(T, L_full))   
    return F

In [39]:
fidelity_calc(sigmax(), sigmay())

4.0

In [40]:
fidelity_calc(sigmay(), sigmay())

0.0

In [41]:
xi_vec_test = array([1.0, 2.0])
xi_vec_test

array([1., 2.])

In [42]:
xi_vec_test.size

2

In [43]:
w_vec = [xi**2 for xi in xi_vec_test]
w_vec

[1.0, 4.0]

In [44]:
# F(Ti, omega_1, xi_vec, Lin, dt)
F(sigmax(), 0.5 , xi_vec_test, sigmaz(), 0.001)

-7.998400634493139

In [45]:
def L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt):
    N = xi_vec.size
    L_v = L_vec(omega_1, xi_vec, Lin, dt)
    
    inner_part = L_I(Ti)
    for i in range(N):
        if i == ( N - 1 - k ):
            inner_part = inner_part*x_k(omega_1, Lin )*L_v[k - 1]
        else:
            inner_part = inner_part*L_v[N - 1 - i]
    l_comma_k = inner_part
    return l_comma_k
    

In [46]:
#L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt)
L_comma_k_maker(sigmax(), 0.5 , xi_vec_test, 2, sigmaz(), 0.001)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 9.99991001e-01+0.00000000e+00j -2.99927960e-03-3.49898670e-06j
  -2.99927960e-03+3.49898670e-06j  8.99883703e-06+0.00000000e+00j]
 [ 2.99948056e-03+2.49939255e-06j  9.99589083e-01+1.99918650e-03j
  -8.99750347e-06+2.99899242e-09j -2.99948056e-03-2.49939255e-06j]
 [ 2.99948056e-03-2.49939255e-06j -8.99750347e-06-2.99899242e-09j
   9.99589083e-01-1.99918650e-03j -2.99948056e-03+2.49939255e-06j]
 [ 8.99883703e-06+0.00000000e+00j  2.99927960e-03+3.49898670e-06j
   2.99927960e-03-3.49898670e-06j  9.99991001e-01+0.00000000e+00j]]

In [50]:
def updater(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    xi_vec_size = xi_vec.size # finding the size of xi
    T = T_maker(Ti)
    L_full = L_full_maker(Ti, omega_1, xi_vec, Lin, dt)
    di = []
    for k in range(xi_vec_size):
        L_comma_k = L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt)
        differentiated = T - L_comma_k
        plain = T - L_full
        c = differentiated.dag()*plain
        d = plain.dag()*differentiated
        inside = c.tr() + d.tr()
        di.append(epsilon*inside)

    diff = array(di)
    xi_new_vec = xi_vec + diff
    return diff, xi_new_vec
    

In [51]:
#  updater(Ti, omega_1, xi_vec, Lin, dt)
updater(sigmax(), 0.5 , xi_vec_test, sigmaz(), 0.001)

NameError: name 'epsilon' is not defined

In [52]:
def terminator(max_iter, time_steps, Ti, omega_1, Lin, total_time):
    r"""Brief description of the function"""
    
    xi_initial =  1000*random_sample((time_steps,))
    dt = total_time/time_steps
    xi_diff, xi_new_vec = updater(Ti, omega_1, xi_initial, Lin, dt)
    
    #xi_diff = xi_new_vec - xi_initial
    for i in range(max_iter):
        if amax(xi_diff) < epsilon**2 :
            xi_final = xi_new_vec
            break
        else :
            xi_diff, xi_new_vec = updater(Ti, omega_1, xi_new_vec, Lin, dt)
            print(i)
            print(amax(xi_diff))
            
        
    xi_final = xi_new_vec    
    return xi_final

In [91]:
omega_1 = 0.5
total_time = pi/omega_1
epsilon = 10**(-6)
max_iter = 10**4#1000#100#50#20
time_steps = 20
dt = total_time/time_steps

In [92]:
Lin = sigmaz() # Lindbladian

In [93]:
Ti = sigmax() # Target unitary

In [ ]:
# terminator(20, 20, Ti, omega_1, Lin, total_time)
xi_opt = terminator(max_iter, time_steps, Ti, omega_1, Lin, total_time)
xi_opt

0
(6.568419973599951e-06+0j)
1
(6.568419909612472e-06+0j)
2
(6.568419845625019e-06+0j)
3
(6.568419781636809e-06+0j)
4
(6.568419717649897e-06+0j)
5
(6.568419653662614e-06+0j)
6
(6.568419589675297e-06+0j)
7
(6.5684195256881915e-06+0j)
8
(6.568419461701252e-06+0j)
9
(6.568419397714036e-06+0j)
10
(6.568419333727224e-06+0j)
11
(6.568419269740304e-06+0j)
12
(6.5684192057536795e-06+0j)
13
(6.568419141767304e-06+0j)
14
(6.568419077780791e-06+0j)
15
(6.56841901379466e-06+0j)
16
(6.5684189498083605e-06+0j)
17
(6.568418885822277e-06+0j)
18
(6.568418821836342e-06+0j)
19
(6.5684187578508055e-06+0j)
20
(6.568418693864719e-06+0j)
21
(6.568418629879141e-06+0j)
22
(6.5684185658932445e-06+0j)
23
(6.568418501907722e-06+0j)
24
(6.5684184379223794e-06+0j)
25
(6.568418373937331e-06+0j)
26
(6.568418309952043e-06+0j)
27
(6.568418245966901e-06+0j)
28
(6.568418181981897e-06+0j)
29
(6.5684181179971476e-06+0j)
30
(6.568418054012477e-06+0j)
31
(6.568417990027864e-06+0j)
32
(6.568417926043165e-06+0j)
33
(6.56841786

268
(6.568402828967192e-06+0j)
269
(6.568402765012304e-06+0j)
270
(6.5684027010569e-06+0j)
271
(6.568402637101897e-06+0j)
272
(6.5684025731471334e-06+0j)
273
(6.568402509192319e-06+0j)
274
(6.568402445237783e-06+0j)
275
(6.568402381283663e-06+0j)
276
(6.5684023173289515e-06+0j)
277
(6.568402253374938e-06+0j)
278
(6.568402189420937e-06+0j)
279
(6.568402125467138e-06+0j)
280
(6.568402061513057e-06+0j)
281
(6.568401997559624e-06+0j)
282
(6.568401933606351e-06+0j)
283
(6.568401869652973e-06+0j)
284
(6.568401805699736e-06+0j)
285
(6.568401741746776e-06+0j)
286
(6.568401677794087e-06+0j)
287
(6.568401613841095e-06+0j)
288
(6.5684015498886105e-06+0j)
289
(6.5684014859362355e-06+0j)
290
(6.568401421983992e-06+0j)
291
(6.568401358031807e-06+0j)
292
(6.568401294080164e-06+0j)
293
(6.5684012301281486e-06+0j)
294
(6.5684011661760955e-06+0j)
295
(6.568401102224747e-06+0j)
296
(6.568401038273417e-06+0j)
297
(6.568400974322205e-06+0j)
298
(6.568400910370766e-06+0j)
299
(6.568400846420144e-06+0j)
300


532
(6.56838595017216e-06+0j)
533
(6.5683858862600005e-06+0j)
534
(6.5683858223475386e-06+0j)
535
(6.56838575843568e-06+0j)
536
(6.56838569452394e-06+0j)
537
(6.568385630612327e-06+0j)
538
(6.568385566700478e-06+0j)
539
(6.568385502789618e-06+0j)
540
(6.568385438878333e-06+0j)
541
(6.568385374967303e-06+0j)
542
(6.568385311056684e-06+0j)
543
(6.56838524714589e-06+0j)
544
(6.568385183235777e-06+0j)
545
(6.568385119325328e-06+0j)
546
(6.568385055415163e-06+0j)
547
(6.56838499150542e-06+0j)
548
(6.568384927595685e-06+0j)
549
(6.568384863686167e-06+0j)
550
(6.5683847997767335e-06+0j)
551
(6.568384735867933e-06+0j)
552
(6.568384671958938e-06+0j)
553
(6.568384608050376e-06+0j)
554
(6.568384544141602e-06+0j)
555
(6.568384480233521e-06+0j)
556
(6.568384416325395e-06+0j)
557
(6.568384352417599e-06+0j)
558
(6.568384288509382e-06+0j)
559
(6.568384224601767e-06+0j)
560
(6.568384160694269e-06+0j)
561
(6.568384096787046e-06+0j)
562
(6.5683840328802385e-06+0j)
563
(6.568383968973371e-06+0j)
564
(6.56

796
(6.568369084103977e-06+0j)
797
(6.568369020245292e-06+0j)
798
(6.568368956386674e-06+0j)
799
(6.568368892528119e-06+0j)
800
(6.568368828669797e-06+0j)
801
(6.5683687648118585e-06+0j)
802
(6.568368700954217e-06+0j)
803
(6.568368637096643e-06+0j)
804
(6.568368573239487e-06+0j)
805
(6.568368509382457e-06+0j)
806
(6.568368445525402e-06+0j)
807
(6.568368381668957e-06+0j)
808
(6.568368317812573e-06+0j)
809
(6.568368253956336e-06+0j)
810
(6.5683681901005535e-06+0j)
811
(6.568368126244241e-06+0j)
812
(6.568368062389048e-06+0j)
813
(6.568367998533989e-06+0j)
814
(6.568367934678921e-06+0j)
815
(6.568367870824106e-06+0j)
816
(6.568367806969541e-06+0j)
817
(6.5683677431150254e-06+0j)
818
(6.568367679260639e-06+0j)
819
(6.568367615407225e-06+0j)
820
(6.568367551553378e-06+0j)
821
(6.568367487699932e-06+0j)
822
(6.568367423846145e-06+0j)
823
(6.56836735999364e-06+0j)
824
(6.568367296140568e-06+0j)
825
(6.568367232288095e-06+0j)
826
(6.568367168436081e-06+0j)
827
(6.568367104584009e-06+0j)
828
(6

1058
(6.568352361151051e-06+0j)
1059
(6.568352297355851e-06+0j)
1060
(6.568352233560766e-06+0j)
1061
(6.568352169766291e-06+0j)
1062
(6.5683521059715695e-06+0j)
1063
(6.5683520421774305e-06+0j)
1064
(6.5683519783835625e-06+0j)
1065
(6.568351914589559e-06+0j)
1066
(6.5683518507960866e-06+0j)
1067
(6.5683517870029055e-06+0j)
1068
(6.5683517232101065e-06+0j)
1069
(6.5683516594171245e-06+0j)
1070
(6.56835159562471e-06+0j)
1071
(6.568351531832767e-06+0j)
1072
(6.568351468040893e-06+0j)
1073
(6.5683514042491725e-06+0j)
1074
(6.568351340458046e-06+0j)
1075
(6.568351276666609e-06+0j)
1076
(6.568351212876102e-06+0j)
1077
(6.568351149085343e-06+0j)
1078
(6.56835108529514e-06+0j)
1079
(6.5683510215049915e-06+0j)
1080
(6.568350957715036e-06+0j)
1081
(6.568350893925916e-06+0j)
1082
(6.568350830136363e-06+0j)
1083
(6.568350766347483e-06+0j)
1084
(6.568350702558794e-06+0j)
1085
(6.568350638770411e-06+0j)
1086
(6.568350574982307e-06+0j)
1087
(6.568350511194442e-06+0j)
1088
(6.568350447406576e-06+0j)
1

1314
(6.568336038519362e-06+0j)
1315
(6.568335974796072e-06+0j)
1316
(6.568335911073445e-06+0j)
1317
(6.568335847349946e-06+0j)
1318
(6.568335783627586e-06+0j)
1319
(6.5683357199056755e-06+0j)
1320
(6.568335656183866e-06+0j)
1321
(6.568335592462245e-06+0j)
1322
(6.568335528740913e-06+0j)
1323
(6.568335465019998e-06+0j)
1324
(6.568335401299136e-06+0j)
1325
(6.568335337579007e-06+0j)
1326
(6.568335273858719e-06+0j)
1327
(6.568335210139333e-06+0j)
1328
(6.5683351464196045e-06+0j)
1329
(6.568335082700667e-06+0j)
1330
(6.568335018981752e-06+0j)
1331
(6.568334955263229e-06+0j)
1332
(6.568334891544853e-06+0j)
1333
(6.568334827827092e-06+0j)
1334
(6.568334764109501e-06+0j)
1335
(6.568334700391878e-06+0j)
1336
(6.568334636674944e-06+0j)
1337
(6.5683345729582474e-06+0j)
1338
(6.568334509241774e-06+0j)
1339
(6.568334445525959e-06+0j)
1340
(6.568334381809775e-06+0j)
1341
(6.568334318094222e-06+0j)
1342
(6.568334254379005e-06+0j)
1343
(6.56833419066446e-06+0j)
1344
(6.5683341269499345e-06+0j)
1345


1570
(6.568319735534046e-06+0j)
1571
(6.568319671891894e-06+0j)
1572
(6.568319608250461e-06+0j)
1573
(6.568319544609532e-06+0j)
1574
(6.568319480968659e-06+0j)
1575
(6.5683194173280075e-06+0j)
1576
(6.568319353687972e-06+0j)
1577
(6.568319290048104e-06+0j)
1578
(6.568319226408728e-06+0j)
1579
(6.568319162769999e-06+0j)
1580
(6.568319099130931e-06+0j)
1581
(6.568319035492475e-06+0j)
1582
(6.5683189718542265e-06+0j)
1583
(6.568318908216493e-06+0j)
1584
(6.568318844579206e-06+0j)
1585
(6.568318780942074e-06+0j)
1586
(6.568318717305359e-06+0j)
1587
(6.5683186536688656e-06+0j)
1588
(6.568318590032845e-06+0j)
1589
(6.568318526397236e-06+0j)
1590
(6.568318462761832e-06+0j)
1591
(6.56831839912672e-06+0j)
1592
(6.56831833549211e-06+0j)
1593
(6.568318271857698e-06+0j)
1594
(6.5683182082235196e-06+0j)
1595
(6.568318144589961e-06+0j)
1596
(6.568318080956796e-06+0j)
1597
(6.56831801732398e-06+0j)
1598
(6.568317953691372e-06+0j)
1599
(6.568317890058375e-06+0j)
1600
(6.568317826426616e-06+0j)
1601
(6

1826
(6.568303454630359e-06+0j)
1827
(6.568303391079656e-06+0j)
1828
(6.568303327529326e-06+0j)
1829
(6.56830326397916e-06+0j)
1830
(6.5683032004293864e-06+0j)
1831
(6.568303136880159e-06+0j)
1832
(6.568303073331055e-06+0j)
1833
(6.568303009782313e-06+0j)
1834
(6.5683029462345305e-06+0j)
1835
(6.568302882686474e-06+0j)
1836
(6.568302819138862e-06+0j)
1837
(6.568302755591888e-06+0j)
1838
(6.56830269204507e-06+0j)
1839
(6.568302628499039e-06+0j)
1840
(6.568302564952672e-06+0j)
1841
(6.568302501407199e-06+0j)
1842
(6.56830243786211e-06+0j)
1843
(6.56830237431704e-06+0j)
1844
(6.568302310772872e-06+0j)
1845
(6.568302247228768e-06+0j)
1846
(6.5683021836851085e-06+0j)
1847
(6.56830212014175e-06+0j)
1848
(6.5683020565988575e-06+0j)
1849
(6.568301993056208e-06+0j)
1850
(6.568301929513953e-06+0j)
1851
(6.568301865972077e-06+0j)
1852
(6.56830180243104e-06+0j)
1853
(6.5683017388894985e-06+0j)
1854
(6.568301675348892e-06+0j)
1855
(6.56830161180875e-06+0j)
1856
(6.568301548268622e-06+0j)
1857
(6.56

2083
(6.56828713475458e-06+0j)
2084
(6.56828707130425e-06+0j)
2085
(6.5682870078545625e-06+0j)
2086
(6.568286944405259e-06+0j)
2087
(6.568286880956206e-06+0j)
2088
(6.568286817507827e-06+0j)
2089
(6.568286754059525e-06+0j)
2090
(6.568286690611998e-06+0j)
2091
(6.568286627164751e-06+0j)
2092
(6.568286563717816e-06+0j)
2093
(6.568286500271354e-06+0j)
2094
(6.568286436825179e-06+0j)
2095
(6.5682863733799035e-06+0j)
2096
(6.568286309934466e-06+0j)
2097
(6.5682862464895416e-06+0j)
2098
(6.568286183045169e-06+0j)
2099
(6.5682861196012405e-06+0j)
2100
(6.568286056157617e-06+0j)
2101
(6.568285992714315e-06+0j)
2102
(6.568285929271764e-06+0j)
2103
(6.568285865829578e-06+0j)
2104
(6.568285802387515e-06+0j)
2105
(6.568285738945778e-06+0j)
2106
(6.5682856755045505e-06+0j)
2107
(6.568285612064125e-06+0j)
2108
(6.568285548624107e-06+0j)
2109
(6.568285485184212e-06+0j)
2110
(6.568285421744633e-06+0j)
2111
(6.5682853583057525e-06+0j)
2112
(6.568285294866665e-06+0j)
2113
(6.568285231428911e-06+0j)
2114

2339
(6.5682709052713225e-06+0j)
2340
(6.568270841930248e-06+0j)
2341
(6.5682707785902455e-06+0j)
2342
(6.56827071525033e-06+0j)
2343
(6.568270651910825e-06+0j)
2344
(6.568270588572193e-06+0j)
2345
(6.568270525233368e-06+0j)
2346
(6.568270461895254e-06+0j)
2347
(6.568270398557818e-06+0j)
2348
(6.56827033522059e-06+0j)
2349
(6.568270271883788e-06+0j)
2350
(6.568270208547244e-06+0j)
2351
(6.568270145211462e-06+0j)
2352
(6.568270081876045e-06+0j)
2353
(6.568270018541515e-06+0j)
2354
(6.568269955206757e-06+0j)
2355
(6.5682698918726045e-06+0j)
2356
(6.5682698285391285e-06+0j)
2357
(6.56826976520594e-06+0j)
2358
(6.568269701873063e-06+0j)
2359
(6.568269638540837e-06+0j)
2360
(6.5682695752090136e-06+0j)
2361
(6.568269511877682e-06+0j)
2362
(6.568269448547007e-06+0j)
2363
(6.568269385216707e-06+0j)
2364
(6.568269321886394e-06+0j)
2365
(6.568269258556702e-06+0j)
2366
(6.568269195227767e-06+0j)
2367
(6.568269131899031e-06+0j)
2368
(6.568269068570528e-06+0j)
2369
(6.568269005242832e-06+0j)
2370
(

2595
(6.568254704942316e-06+0j)
2596
(6.568254641719599e-06+0j)
2597
(6.568254578497938e-06+0j)
2598
(6.568254515276552e-06+0j)
2599
(6.568254452055633e-06+0j)
2600
(6.5682543888347954e-06+0j)
2601
(6.5682543256151345e-06+0j)
2602
(6.568254262395663e-06+0j)
2603
(6.568254199176411e-06+0j)
2604
(6.5682541359583285e-06+0j)
2605
(6.568254072739898e-06+0j)
2606
(6.568254009522215e-06+0j)
2607
(6.568253946305086e-06+0j)
2608
(6.568253883088766e-06+0j)
2609
(6.568253819872575e-06+0j)
2610
(6.568253756656813e-06+0j)
2611
(6.56825369344168e-06+0j)
2612
(6.568253630226957e-06+0j)
2613
(6.568253567012751e-06+0j)
2614
(6.568253503799088e-06+0j)
2615
(6.568253440585852e-06+0j)
2616
(6.568253377373047e-06+0j)
2617
(6.568253314160657e-06+0j)
2618
(6.568253250949171e-06+0j)
2619
(6.568253187737363e-06+0j)
2620
(6.568253124526866e-06+0j)
2621
(6.5682530613165415e-06+0j)
2622
(6.568252998106677e-06+0j)
2623
(6.56825293489749e-06+0j)
2624
(6.568252871688403e-06+0j)
2625
(6.568252808479792e-06+0j)
2626
(

2851
(6.5682385360370485e-06+0j)
2852
(6.568238472941689e-06+0j)
2853
(6.5682384098469634e-06+0j)
2854
(6.568238346752773e-06+0j)
2855
(6.568238283659082e-06+0j)
2856
(6.5682382205657666e-06+0j)
2857
(6.568238157473224e-06+0j)
2858
(6.568238094381105e-06+0j)
2859
(6.568238031289443e-06+0j)
2860
(6.568237968198369e-06+0j)
2861
(6.568237905107384e-06+0j)
2862
(6.5682378420172286e-06+0j)
2863
(6.568237778927784e-06+0j)
2864
(6.568237715838797e-06+0j)
2865
(6.568237652750388e-06+0j)
2866
(6.568237589662407e-06+0j)
2867
(6.568237526574826e-06+0j)
2868
(6.568237463487701e-06+0j)
2869
(6.568237400401401e-06+0j)
2870
(6.568237337315233e-06+0j)
2871
(6.568237274229518e-06+0j)
2872
(6.56823721114496e-06+0j)
2873
(6.568237148060726e-06+0j)
2874
(6.5682370849763566e-06+0j)
2875
(6.568237021893326e-06+0j)
2876
(6.568236958810222e-06+0j)
2877
(6.568236895727806e-06+0j)
2878
(6.568236832645803e-06+0j)
2879
(6.568236769564684e-06+0j)
2880
(6.568236706483942e-06+0j)
2881
(6.568236643403336e-06+0j)
2882

3107
(6.568222400781033e-06+0j)
3108
(6.568222337821361e-06+0j)
3109
(6.56822227486241e-06+0j)
3110
(6.56822221190407e-06+0j)
3111
(6.568222148946161e-06+0j)
3112
(6.568222085988928e-06+0j)
3113
(6.5682220230319145e-06+0j)
3114
(6.568221960076025e-06+0j)
3115
(6.568221897120143e-06+0j)
3116
(6.568221834164929e-06+0j)
3117
(6.568221771210305e-06+0j)
3118
(6.5682217082563186e-06+0j)
3119
(6.568221645302985e-06+0j)
3120
(6.568221582349922e-06+0j)
3121
(6.568221519397856e-06+0j)
3122
(6.568221456445856e-06+0j)
3123
(6.5682213934947545e-06+0j)
3124
(6.568221330543808e-06+0j)
3125
(6.568221267594121e-06+0j)
3126
(6.568221204643854e-06+0j)
3127
(6.568221141694813e-06+0j)
3128
(6.568221078746198e-06+0j)
3129
(6.568221015798451e-06+0j)
3130
(6.568220952850842e-06+0j)
3131
(6.568220889903903e-06+0j)
3132
(6.568220826958114e-06+0j)
3133
(6.568220764012203e-06+0j)
3134
(6.568220701067023e-06+0j)
3135
(6.568220638121782e-06+0j)
3136
(6.568220575178049e-06+0j)
3137
(6.568220512234212e-06+0j)
3138
(6

3363
(6.568206301354643e-06+0j)
3364
(6.568206238539419e-06+0j)
3365
(6.568206175724629e-06+0j)
3366
(6.5682061129103506e-06+0j)
3367
(6.568206050096719e-06+0j)
3368
(6.568205987283921e-06+0j)
3369
(6.56820592447149e-06+0j)
3370
(6.5682058616596464e-06+0j)
3371
(6.56820579884823e-06+0j)
3372
(6.568205736037974e-06+0j)
3373
(6.5682056732277144e-06+0j)
3374
(6.5682056104183046e-06+0j)
3375
(6.568205547608902e-06+0j)
3376
(6.568205484800695e-06+0j)
3377
(6.568205421993191e-06+0j)
3378
(6.568205359185913e-06+0j)
3379
(6.568205296379252e-06+0j)
3380
(6.5682052335730744e-06+0j)
3381
(6.568205170767887e-06+0j)
3382
(6.568205107963021e-06+0j)
3383
(6.568205045158539e-06+0j)
3384
(6.568204982354587e-06+0j)
3385
(6.568204919551518e-06+0j)
3386
(6.568204856749057e-06+0j)
3387
(6.568204793947255e-06+0j)
3388
(6.568204731146135e-06+0j)
3389
(6.568204668344886e-06+0j)
3390
(6.5682046055450095e-06+0j)
3391
(6.568204542745113e-06+0j)
3392
(6.568204479946245e-06+0j)
3393
(6.568204417147937e-06+0j)
3394

3619
(6.568190239893533e-06+0j)
3620
(6.568190177230714e-06+0j)
3621
(6.568190114568803e-06+0j)
3622
(6.568190051906601e-06+0j)
3623
(6.5681899892459174e-06+0j)
3624
(6.568189926585378e-06+0j)
3625
(6.568189863925715e-06+0j)
3626
(6.568189801266165e-06+0j)
3627
(6.568189738607712e-06+0j)
3628
(6.5681896759496146e-06+0j)
3629
(6.568189613292139e-06+0j)
3630
(6.568189550635452e-06+0j)
3631
(6.568189487979453e-06+0j)
3632
(6.5681894253241105e-06+0j)
3633
(6.56818936266884e-06+0j)
3634
(6.568189300014454e-06+0j)
3635
(6.5681892373608935e-06+0j)
3636
(6.568189174707997e-06+0j)
3637
(6.568189112055499e-06+0j)
3638
(6.5681890494034075e-06+0j)
3639
(6.5681889867523284e-06+0j)
3640
(6.56818892410152e-06+0j)
3641
(6.568188861451147e-06+0j)
3642
(6.5681887988020854e-06+0j)
3643
(6.568188736153336e-06+0j)
3644
(6.568188673505321e-06+0j)
3645
(6.568188610857725e-06+0j)
3646
(6.5681885482108e-06+0j)
3647
(6.5681884855645344e-06+0j)
3648
(6.568188422918215e-06+0j)
3649
(6.5681883602732784e-06+0j)
365

In [ ]:
F(Ti, omega_1, xi_opt, Lin, dt)

In [ ]:
max_iter

In [ ]:
T = T_maker(Ti)
T

In [ ]:
L_full_maker(Ti, omega_1, xi_opt, Lin, dt)

In [ ]:
hinton(L_full_maker(Ti, omega_1, xi_opt, Lin, dt))

In [12]:
1.31350478e-05 # 40

1.31350478e-05

In [13]:
1.31390107e-05 # 50

1.31390107e-05

In [14]:
α = 2

In [15]:
new_array = random_sample((4,3,))

NameError: name 'random_sample' is not defined

In [ ]:
new_array

In [ ]:
new_array.any()

In [ ]:
new_array[0] = 0


In [ ]:
new_array

In [ ]:
new_array.any()

In [ ]:
new_array.all()

In [ ]:
max(new_array)

In [ ]:
max(new_array, axis=0)

In [ ]:
from numpy import amax 

In [ ]:
amax(new_array)