# Imports

## Qutip imports 1

In [1]:
from qutip.operators import sigmax, sigmay, sigmaz, identity
# position, momentum, num, create, destroy, commutator, qeye 
from qutip.tensor import tensor
from qutip.qip.gates import swap, rx, ry, rz
from qutip.qobj import Qobj
from qutip.visualization import hinton
from qutip.visualization import matrix_histogram_complex, matrix_histogram
from qutip.random_objects import rand_herm, rand_unitary, rand_dm

## Qutip imports 2

In [2]:
from 

SyntaxError: invalid syntax (<ipython-input-2-09c8a0c03c80>, line 1)

## Numpy imports 

In [3]:
from numpy import sin, cos, tan, real, imag,  log, conj
from numpy import array, append, linspace, arange
from numpy import add, sqrt, abs, dot
from numpy.random import random, random_sample, random
from numpy import concatenate, trace
from numpy import ones, zeros, ones_like, zeros_like
from numpy import amax, amin, nanmax, nanmin
# from numpy import pi

## Scipy imports

In [4]:
from scipy.integrate import ode, odeint, complex_ode
from scipy.optimize import minimize
from scipy.linalg import eigh, inv, norm, expm
# from scipy.linalg import 
# from scipy import

## Matplotlib imports

In [5]:
from matplotlib.pyplot import plot, figure, show, savefig, axes
from matplotlib.pyplot import xlabel, ylabel, title, legend
from matplotlib import rcParams
from matplotlib.pyplot import style 
from matplotlib.pyplot import xlim, ylim, axis 
# beware not same as axes
from matplotlib.pyplot import subplot, subplots, text
from matplotlib.pyplot import GridSpec



pgf_with_rc_fonts = {"pgf.texsystem": "pdflatex"}
rcParams.update(pgf_with_rc_fonts)
style.use('seaborn-whitegrid')



## Math imports

In [6]:
from math import pi
from math import exp

## Cmath imports

## Date and datetime imports

In [7]:
from datetime import date
from datetime import datetime# now


## Os imports

In [8]:
from os import getcwd, mkdir, chdir
from os.path import abspath, join 


## Sympy imports

In [9]:
from sympy import Function, dsolve, Eq, Derivative, symbols
# x, y, z, t = symbols('x y z t')
# k, m, n = symbols('k m n', integer=True)
# f, g, h = symbols('f g h', cls=Function)

## Miscellaneous imports

## Extra useful functions

In [10]:
def rint(x):
    print("x = ", x)
    return None

# Building parts

In [11]:
 del omega_1, total_time, epsilon, 
omega_1 = 0.5
total_time = 2*pi/omega_1
epsilon = 10**(-6)
max_iter = 100
time_steps = 200
dt = total_time/time_steps

NameError: name 'omega_1' is not defined

In [12]:
del Lin, Ti

NameError: name 'Lin' is not defined

In [13]:
Lin

NameError: name 'Lin' is not defined

## level 1

In [14]:
def H1(omega_1):
    r"""Brief description of the function"""
    H1 = omega_1*sigmaz()
    return H1


In [15]:
def H2():
    r"""Brief description of the function"""
    H2 = sigmay()
    return H2

In [42]:
#I = identity(2)
del I

In [43]:
def T_maker(Ti):
    r"""Brief description of the function"""
    T = tensor(Ti.trans(), Ti)
    return T

In [44]:
 tensor(identity(2), T_maker(sigmax()))

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]

## level 2

In [45]:
def Hamil(omega_1, xi):
    H = H1(omega_1) + xi*H2()
    return H

In [46]:
Hamil(2, 0.5 )

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 2.+0.j   0.-0.5j]
 [ 0.+0.5j -2.+0.j ]]

In [47]:
def leftover(Lin):
    r"""Brief description of the function"""
    d = Lin.shape[0]
    I = identity(d)
    term1 = tensor(Lin.trans(), Lin)
    term2 = tensor(I, ((Lin.dag())*(Lin)))
    term3 = tensor(((Lin.trans())*(Lin.conj())), I)
    leftover = 1j*(0.1)*(term1 - 0.5*(term2 + term2))
    return leftover


    return x**2
def A(omega_1, xi, Lin):
    H = Hamil(omega_1, xi)
    d = Lin.shape[0]
    I = identity(d)
    A = tensor(I, H) - tensor((H.conj()), I) + leftover(Lin)
    return A

In [48]:
A(2, 0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.+0.j   0.-0.5j  0.-0.5j  0.+0.j ]
 [ 0.+0.5j -4.-0.2j  0.+0.j   0.-0.5j]
 [ 0.+0.5j  0.+0.j   4.-0.2j  0.-0.5j]
 [ 0.+0.j   0.+0.5j  0.+0.5j  0.+0.j ]]

In [49]:
A(0, 0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.+0.j  0.-0.5j 0.-0.5j 0.+0.j ]
 [0.+0.5j 0.-0.2j 0.+0.j  0.-0.5j]
 [0.+0.5j 0.+0.j  0.-0.2j 0.-0.5j]
 [0.+0.j  0.+0.5j 0.+0.5j 0.+0.j ]]

In [50]:
I

NameError: name 'I' is not defined

In [51]:
#term1 = tensor(Lin.trans(), Lin)
#term2 = tensor(I, ((Lin.dag())*(Lin)))
#term3 = tensor(((Lin.trans())*(Lin.conj())), I)
#leftover = 1j*(0.1)*(term1 - 0.5*(term2 + term2))
def x_k(omega_1, Lin ):
    r"""Brief description of the function"""
    #H11 = H1(omega_1)
    #H2_i = H2()
    d = Lin.shape[0]
    I = identity(d)
    x_k = tensor(I, H2()) - tensor((H2().conj()), I) + leftover(Lin)
    return x_k


In [52]:
I

NameError: name 'I' is not defined

In [53]:
x_k(0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.+0.j  0.-1.j  0.-1.j  0.+0.j ]
 [0.+1.j  0.-0.2j 0.+0.j  0.-1.j ]
 [0.+1.j  0.+0.j  0.-0.2j 0.-1.j ]
 [0.+0.j  0.+1.j  0.+1.j  0.+0.j ]]

In [54]:
def L(omega_1, xi, Lin, dt):
    #H = H1
    L = (-1j*A(omega_1, xi, Lin)*dt).expm()
    return L

In [55]:
L(0.5, 2, sigmaz(), 0.001)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 9.99996000e-01+0.00000000e+00j -1.99979435e-03-9.99865260e-07j
  -1.99979435e-03+9.99865260e-07j  3.99972768e-06+0.00000000e+00j]
 [ 1.99979435e-03+9.99865260e-07j  9.99795521e-01+9.99797187e-04j
  -3.99946104e-06+0.00000000e+00j -1.99979435e-03-9.99865260e-07j]
 [ 1.99979435e-03-9.99865260e-07j -3.99946104e-06+0.00000000e+00j
   9.99795521e-01-9.99797187e-04j -1.99979435e-03+9.99865260e-07j]
 [ 3.99972768e-06+0.00000000e+00j  1.99979435e-03+9.99865260e-07j
   1.99979435e-03-9.99865260e-07j  9.99996000e-01+0.00000000e+00j]]

In [57]:
def L_I(Ti):
    r"""Brief description of the function"""
    d = Ti.shape[0]
    I = identity(d)
    L_I = tensor(I, I)
    return L_I

In [59]:
L_I(sigmay())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

## parameters

### sub sub topic 1

In [62]:
# building the function to optimize (optimizee)
def L_vec(omega_1, xi_vec, Lin, dt):
    #xi_vec_size = 2#xi_vec.size # finding the size of xi
    L_vec = [L(omega_1, xi, Lin, dt) for xi in xi_vec] 
    # constructing L #[L(1.0), L(2.0)]
    
    return L_vec


In [63]:
def fidelity_calc(A, B):
    r"""Brief description of the function"""
    d1 = A.shape[0] # Assuming no rectangular shaped matrices
    d2 = B.shape[0] # Assuming no rectangular shaped matrices
    d = d1*d2
    first_part = (A - B).dag()
    second_part = (A - B)
    f_int = (first_part* second_part)/d
    f = f_int.tr()
    return f

In [81]:
def L_full_maker(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    xi_vec_size = xi_vec.size # finding the size of xi
    L_full = L_I(Ti) # Identity for the for loop of L
    L_v = L_vec(omega_1, xi_vec, Lin, dt) # calling L_vec
    for i in range(xi_vec_size): # generating L_full
        L_full = L_full*L_v[xi_vec_size - 1 - i]
    return L_full

In [83]:
def F(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    L_full = L_full_maker(Ti, omega_1, xi_vec, Lin, dt)
    T = T_maker(Ti)
    F = real(fidelity_calc(T, L_full))   
    return F

In [84]:
fidelity_calc(sigmax(), sigmay())

1.0

In [85]:
fidelity_calc(sigmay(), sigmay())

0.0

In [86]:
xi_vec_test = array([1.0, 2.0])
xi_vec_test

array([1., 2.])

In [87]:
xi_vec_test.size

2

In [88]:
w_vec = [xi**2 for xi in xi_vec_test]
w_vec

[1.0, 4.0]

In [100]:
# F(Ti, omega_1, xi_vec, Lin, dt)
F(sigmax(), 0.5 , xi_vec_test, sigmaz(), 0.001)

0.4999000396558212

In [101]:
def L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt):
    N = xi_vec.size
    L_v = L_vec(omega_1, xi_vec, Lin, dt)
    
    inner_part = L_I(Ti)
    for i in range(N):
        if i == ( N - 1 - k ):
            inner_part = inner_part*x_k(omega_1, Lin )*L_v[k - 1]
        else:
            inner_part = inner_part*L_v[N - 1 - i]
    l_comma_k = inner_part
    return l_comma_k
    

In [105]:
#L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt)
L_comma_k_maker(sigmax(), 0.5 , xi_vec_test, 2, sigmaz(), 0.001)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 9.99991001e-01+0.00000000e+00j -2.99927960e-03-3.49898670e-06j
  -2.99927960e-03+3.49898670e-06j  8.99883703e-06+0.00000000e+00j]
 [ 2.99948056e-03+2.49939255e-06j  9.99589083e-01+1.99918650e-03j
  -8.99750347e-06+2.99899242e-09j -2.99948056e-03-2.49939255e-06j]
 [ 2.99948056e-03-2.49939255e-06j -8.99750347e-06-2.99899242e-09j
   9.99589083e-01-1.99918650e-03j -2.99948056e-03+2.49939255e-06j]
 [ 8.99883703e-06+0.00000000e+00j  2.99927960e-03+3.49898670e-06j
   2.99927960e-03-3.49898670e-06j  9.99991001e-01+0.00000000e+00j]]

In [108]:
def updater(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    xi_vec_size = xi_vec.size # finding the size of xi
    T = T_maker(Ti)
    L_full = L_full_maker(Ti, omega_1, xi_vec, Lin, dt)
    di = []
    for k in range(xi_vec_size):
        L_comma_k = L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt)
        differentiated = T - L_comma_k
        plain = T - L_full
        c = differentiated.dag()*plain
        d = plain.dag()*differentiated
        inside = c.tr() + d.tr()
        di.append(epsilon*2*real(inside))

    diff = array(di)
    xi_new_vec = xi_vec + diff
    return diff, xi_new_vec
    

In [109]:
#  updater(Ti, omega_1, xi_vec, Lin, dt)
updater(sigmax(), 0.5 , xi_vec_test, sigmaz(), 0.001)

(array([1.6e-05, 1.6e-05]), array([1.000016, 2.000016]))

In [110]:
def terminator(max_iter, time_steps, Ti, omega_1, Lin, total_time):
    r"""Brief description of the function"""
    xi_initial =  random_sample((time_steps,))
    dt = total_time/time_steps
    xi_diff, xi_new_vec = updater(Ti, omega_1, xi_initial, Lin, dt)
    
    #xi_diff = xi_new_vec - xi_initial
    for i in range(max_iter):
        if amax(xi_diff) < epsilon**2 :
            xi_final = xi_new_vec
            break
        else :
            xi_diff, xi_new_vec = updater(Ti, omega_1, xi_new_vec, Lin, dt)
            
        
    xi_final = xi_new_vec    
    return xi_final

In [115]:
omega_1 = 0.5
total_time = pi/omega_1
epsilon = 10**(-6)
max_iter = 20
time_steps = 20
dt = total_time/time_steps

In [116]:
Lin = sigmaz() # Lindbladian

In [117]:
Ti = sigmax() # Target unitary

In [118]:
# terminator(20, 20, Ti, omega_1, Lin, total_time)
xi_opt = terminator(max_iter, time_steps, Ti, omega_1, Lin, total_time)
xi_opt

array([0.6299679 , 0.2139935 , 0.71163375, 0.64106488, 0.81312017,
       0.97517941, 0.13013848, 0.36989815, 0.48933509, 0.2890539 ,
       0.84370867, 0.81973979, 0.58242431, 0.5910745 , 0.79887339,
       0.43176648, 0.86794939, 0.93081163, 0.59964603, 0.63874329])

In [119]:
F(Ti, omega_1, xi_opt, Lin, dt)

0.27115222010914664

In [120]:
max_iter

200

In [113]:
α = 2

In [114]:
new_array = random_sample((4,3,))

In [78]:
new_array

array([[0.5727494 , 0.38293601, 0.36874311],
       [0.92736909, 0.71153787, 0.61927054],
       [0.77571877, 0.06657134, 0.25520209],
       [0.27701559, 0.31532412, 0.21852523]])

In [79]:
new_array.any()

True

In [80]:
new_array[0] = 0


In [81]:
new_array

array([[0.        , 0.        , 0.        ],
       [0.92736909, 0.71153787, 0.61927054],
       [0.77571877, 0.06657134, 0.25520209],
       [0.27701559, 0.31532412, 0.21852523]])

In [82]:
new_array.any()

True

In [83]:
new_array.all()

False

In [84]:
max(new_array)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
max(new_array, axis=0)

TypeError: 'axis' is an invalid keyword argument for this function

In [86]:
from numpy import amax 

In [87]:
amax(new_array)

0.9273690900033358