# Imports

## Qutip imports 1

In [44]:
from qutip.operators import sigmax, sigmay, sigmaz, identity
# position, momentum, num, create, destroy, commutator, qeye 
from qutip.tensor import tensor
from qutip.qip.gates import swap, rx, ry, rz
from qutip.qobj import Qobj
from qutip.visualization import hinton
from qutip.visualization import matrix_histogram_complex, matrix_histogram
from qutip.random_objects import rand_herm, rand_unitary, rand_dm

## Qutip imports 2

In [45]:
from 

SyntaxError: invalid syntax (<ipython-input-45-09c8a0c03c80>, line 1)

## Numpy imports 

In [46]:
from numpy import sin, cos, tan, real, imag,  log, conj
from numpy import array, append, linspace, arange
from numpy import add, sqrt, abs, dot
from numpy.random import random, random_sample, random
from numpy import concatenate, trace
from numpy import ones, zeros, ones_like, zeros_like
# from numpy import pi

## Scipy imports

In [47]:
from scipy.integrate import ode, odeint, complex_ode
from scipy.optimize import minimize
from scipy.linalg import eigh, inv, norm, expm
# from scipy.linalg import 
# from scipy import

## Matplotlib imports

In [48]:
from matplotlib.pyplot import plot, figure, show, savefig, axes
from matplotlib.pyplot import xlabel, ylabel, title, legend
from matplotlib import rcParams
from matplotlib.pyplot import style 
from matplotlib.pyplot import xlim, ylim, axis 
# beware not same as axes
from matplotlib.pyplot import subplot, subplots, text
from matplotlib.pyplot import GridSpec



pgf_with_rc_fonts = {"pgf.texsystem": "pdflatex"}
rcParams.update(pgf_with_rc_fonts)
style.use('seaborn-whitegrid')



## Math imports

In [49]:
from math import pi
from math import exp

## Cmath imports

## Date and datetime imports

In [50]:
from datetime import date
from datetime import datetime# now


## Os imports

In [51]:
from os import getcwd, mkdir, chdir
from os.path import abspath, join 


## Sympy imports

In [52]:
from sympy import Function, dsolve, Eq, Derivative, symbols
# x, y, z, t = symbols('x y z t')
# k, m, n = symbols('k m n', integer=True)
# f, g, h = symbols('f g h', cls=Function)

## Miscellaneous imports

## Extra useful functions

In [53]:
def rint(x):
    print("x = ", x)
    return None

# Building parts

In [85]:
omega_1 = 0.5
total_time = 2*pi/omega_1
epsilon = 10**(-6)
max_iter = 100
time_steps = 200
dt = total_time/time_steps

## level 1

In [87]:
H1 = omega_1*sigmaz()
H1

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5  0. ]
 [ 0.  -0.5]]

In [57]:
H2 = sigmay()

In [58]:
Lin = sigmaz() # Lindbladian

In [59]:
Ti = sigmax() # Target unitary

In [60]:
I = identity(2)

In [61]:
def T_maker(Ti):
    r"""Brief description of the function"""
    T = tensor(Ti.trans(), Ti)
    return T

In [62]:
 tensor(I,T_maker(Ti))

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]

## level 2

In [63]:
def Hamil(xi, H1, H2):
    H = H1 + xi*H2
    return H

In [64]:
Hamil(2, H1, H2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.+0.j  0.-2.j]
 [ 0.+2.j -1.+0.j]]

In [65]:
def leftover(Lin):
    r"""Brief description of the function"""
    term1 = tensor(Lin.trans(), Lin)
    term2 = tensor(I, ((Lin.dag())*(Lin)))
    term3 = tensor(((Lin.trans())*(Lin.conj())), I)
    leftover = 1j*(0.1)*(term1 - 0.5*(term2 + term2))
    return leftover


    return x**2
def A(xi, H1, H2, Lin):
    H = I
    H = Hamil(xi, H1, H2)
    
    A = tensor(I, H) - tensor((H.conj()), I) + leftover(Lin)
    return A

In [66]:
A(2, H1, H2, Lin)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.+0.j   0.-2.j   0.-2.j   0.+0.j ]
 [ 0.+2.j  -2.-0.2j  0.+0.j   0.-2.j ]
 [ 0.+2.j   0.+0.j   2.-0.2j  0.-2.j ]
 [ 0.+0.j   0.+2.j   0.+2.j   0.+0.j ]]

In [67]:
A(0, H1, H2, Lin)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.+0.j   0.+0.j   0.+0.j   0.+0.j ]
 [ 0.+0.j  -2.-0.2j  0.+0.j   0.+0.j ]
 [ 0.+0.j   0.+0.j   2.-0.2j  0.+0.j ]
 [ 0.+0.j   0.+0.j   0.+0.j   0.+0.j ]]

In [68]:
#term1 = tensor(Lin.trans(), Lin)
#term2 = tensor(I, ((Lin.dag())*(Lin)))
#term3 = tensor(((Lin.trans())*(Lin.conj())), I)
#leftover = 1j*(0.1)*(term1 - 0.5*(term2 + term2))
def x_k(H2, Lin ):
    r"""Brief description of the function"""
    x_k = tensor(I, H2) - tensor((H2.conj()), I) + leftover(Lin)
    return x_k


In [69]:
def L(xi, H1, H2, Lin, dt):
    #H = H1
    L = (-1j*A(xi, H1, H2, Lin)*dt).expm()
    return L

In [70]:
L(2, H1, H2, Lin, dt)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.48808011+0.j          0.38100514-0.21146373j  0.38100514+0.21146373j
   0.51191989+0.j        ]
 [-0.38100514+0.21146373j  0.22572447-0.40215151j -0.42292746+0.j
   0.38100514-0.21146373j]
 [-0.38100514-0.21146373j -0.42292746+0.j          0.22572447+0.40215151j
   0.38100514+0.21146373j]
 [ 0.51191989+0.j         -0.38100514+0.21146373j -0.38100514-0.21146373j
   0.48808011+0.j        ]]

In [71]:
L(2.7, H1, H2, Lin, dt)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.88590935+0.j          0.21028447-0.00985507j  0.21028447+0.00985507j
   0.11409065+0.j        ]
 [-0.21028447+0.00985507j  0.80670398-0.15649628j -0.0266087 +0.j
   0.21028447-0.00985507j]
 [-0.21028447-0.00985507j -0.0266087 +0.j          0.80670398+0.15649628j
   0.21028447+0.00985507j]
 [ 0.11409065+0.j         -0.21028447+0.00985507j -0.21028447-0.00985507j
   0.88590935+0.j        ]]

In [72]:
L_I = tensor(I,I)

In [73]:
L_I

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

## parameters

### sub sub topic 1

In [74]:
# building the function to optimize (optimizee)
def L_vec(xi_vec, H1, H2, Lin, dt):
    #xi_vec_size = 2#xi_vec.size # finding the size of xi
    L_vec = [L(xi, H1, H2, Lin, dt) for xi in xi_vec] # constructing L #[L(1.0), L(2.0)]
    
    return L_vec

def optimizee(xi_vec, Ti, H1, H2, Lin, dt):
    xi_vec_size = xi_vec.size # finding the size of xi
    L_full = L_I # Identity for the for loop of L
    L_v = L_vec(xi_vec, H1, H2, Lin, dt) # calling L_vec
    for i in range(xi_vec_size): # generating L_full
        L_full = L_full*L_v[xi_vec_size - 1 - i]
    T = T_maker(Ti)
    tr_innard = (T.dag())*L_full # argument of the trace
    # Calculating the trace    
    optim_fid = real((tr_innard).tr())    
    return optim_fid

In [75]:
xi_vec_test = array([1.0, 2.0])
xi_vec_test

array([1., 2.])

In [76]:
xi_vec_test.size

2

In [77]:
w_vec = [xi**2 for xi in xi_vec_test]
w_vec

[1.0, 4.0]

In [78]:
optimizee(xi_vec_test, Ti, H1, H2, Lin, dt)

0.4135894995907217

In [79]:
def fid_measure(xi, Ti, H1, H2, Lin, dt):
    phi = optimizee(xi, Ti, H1, H2, Lin, dt)
    fid = conj(phi)*phi
    return fid

In [80]:
fid_measure(xi_vec_test, Ti, H1, H2, Lin, dt)

0.1710562741717036

In [81]:
def phi_k(xi_vec, k, Ti,  H1, H2, Lin, dt):
    N = xi_vec.size
    L_v = L_vec(xi_vec, H1, H2, Lin, dt)
    T = T_maker(Ti)
    inner_part = T.dag()
    for i in range(N):
        if i == ( N - 1 - k ):
            inner_part = inner_part*x_k(H2, Lin )*L_v[k - 1]
        else:
            inner_part = inner_part*L_v[N - 1 - i]
    phi_k = inner_part.tr()
    return phi_k
    

In [82]:
def updater(xi_vec, Ti,  H1, H2, Lin, dt):
    r"""Brief description of the function"""
    xi_vec_size = xi_vec.size # finding the size of xi
    di = []
    for k in range(xi_vec_size):
        part1 = conj(optimizee(xi_vec, Ti,  H1, H2, Lin, dt))
        part2 = phi_k(xi_vec, k, Ti,  H1, H2, Lin, dt)
        inside = (part1)*(part2)
        di.append(epsilon*2*real(inside))

    diff = array(di)
    xi_new_vec = xi_vec + diff
    return xi_new_vec

In [83]:
def terminator(max_iter, time_steps, Ti,  H1, H2, Lin, dt):
    r"""Brief description of the function"""
    xi_final =  random_sample((time_steps,))
    xi_new_vec = updater(xi_final, Ti,  H1, H2, Lin, dt)
    
    xi_diff = xi_new_vec - xi_final
    for i in range(max_iter):
        if max(xi_diff) < epsilon**2 :
            xi_final = xi_new_vec
            break
        else :
            xi_new_vec = updater(xi_vec, Ti,  H1, H2, Lin, dt)
            xi_diff = xi_new_vec - xi_vec
        
    xi_final = xi_new_vec    
    return xi_final

In [86]:
xi_opt = terminator(20000, 200000, Ti,  H1, H2, Lin, dt)
xi_opt

KeyboardInterrupt: 

In [ ]:
fid_measure(xi_opt, Ti, H1, H2, Lin, dt)