# Imports

## Qutip imports 1

In [1]:
from qutip.operators import sigmax, sigmay, sigmaz, identity
# position, momentum, num, create, destroy, commutator, qeye 
from qutip.tensor import tensor
from qutip.qip.gates import swap, rx, ry, rz
from qutip.qobj import Qobj
from qutip.visualization import hinton
from qutip.visualization import matrix_histogram_complex, matrix_histogram
from qutip.random_objects import rand_herm, rand_unitary, rand_dm



## Numpy imports 

In [2]:
from numpy import sin, cos, tan, real, imag,  log, conj
from numpy import array, append, linspace, arange
from numpy import add, sqrt, abs, dot
from numpy.random import random, random_sample, random
from numpy import concatenate, trace
from numpy import ones, zeros, ones_like, zeros_like
from numpy import amax, amin, nanmax, nanmin
# from numpy import pi




## Scipy imports

In [3]:
from scipy.integrate import ode, odeint, complex_ode
from scipy.optimize import minimize
from scipy.linalg import eigh, inv, norm, expm
# from scipy.linalg import 
# from scipy import

## Matplotlib imports

In [4]:
from matplotlib.pyplot import plot, figure, show, savefig, axes
from matplotlib.pyplot import xlabel, ylabel, title, legend
from matplotlib import rcParams
from matplotlib.pyplot import style 
from matplotlib.pyplot import xlim, ylim, axis 
# beware not same as axes
from matplotlib.pyplot import subplot, subplots, text
from matplotlib.pyplot import GridSpec



pgf_with_rc_fonts = {"pgf.texsystem": "pdflatex"}
rcParams.update(pgf_with_rc_fonts)
style.use('seaborn-whitegrid')



## Math imports

In [5]:
from math import pi
from math import exp

## Cmath imports

## Date and datetime imports

In [6]:
from datetime import date
from datetime import datetime# now


## Os imports

In [7]:
from os import getcwd, mkdir, chdir
from os.path import abspath, join 


## Sympy imports

In [8]:
from sympy import Function, dsolve, Eq, Derivative, symbols
# x, y, z, t = symbols('x y z t')
# k, m, n = symbols('k m n', integer=True)
# f, g, h = symbols('f g h', cls=Function)

## Miscellaneous imports

## Extra useful functions

In [9]:
def rint(x):
    print("x = ", x)
    return None

# Building parts

In [10]:
 del omega_1, total_time, epsilon, 
omega_1 = 0.5
total_time = 2*pi/omega_1
epsilon = 10**(-6)
max_iter = 100
time_steps = 200
dt = total_time/time_steps

NameError: name 'omega_1' is not defined

In [11]:
del Lin, Ti

NameError: name 'Lin' is not defined

In [12]:
Lin

NameError: name 'Lin' is not defined

## level 1

In [13]:
def H1(omega_1):
    r"""Brief description of the function"""
    H1 = omega_1*sigmaz()
    return H1


In [14]:
def H2():
    r"""Brief description of the function"""
    H2 = sigmay()
    return H2

In [15]:
#I = identity(2)
del I

NameError: name 'I' is not defined

In [16]:
def T_maker(Ti):
    r"""Brief description of the function"""
    T = tensor(Ti.trans(), Ti)
    return T

In [17]:
 tensor(identity(2), T_maker(sigmax()))

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]

## level 2

In [18]:
def Hamil(omega_1, xi):
    H = H1(omega_1) + xi*H2()
    return H

In [19]:
Hamil(2, 0.5 )

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 2.+0.j   0.-0.5j]
 [ 0.+0.5j -2.+0.j ]]

In [20]:
def leftover(Lin):
    r"""Brief description of the function"""
    d = Lin.shape[0]
    I = identity(d)
    term1 = tensor(Lin.trans(), Lin)
    term2 = tensor(I, ((Lin.dag())*(Lin)))
    term3 = tensor(((Lin.trans())*(Lin.conj())), I)
    leftover = 1j*(0.1)*(term1 - 0.5*(term2 + term3))
    return leftover


def A(omega_1, xi, Lin):
    H = Hamil(omega_1, xi)
    d = Lin.shape[0]
    I = identity(d)
    A = tensor(I, H) - tensor((H.conj()), I) + leftover(Lin)
    return A

In [21]:
A(2, 0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.+0.j   0.-0.5j  0.-0.5j  0.+0.j ]
 [ 0.+0.5j -4.-0.2j  0.+0.j   0.-0.5j]
 [ 0.+0.5j  0.+0.j   4.-0.2j  0.-0.5j]
 [ 0.+0.j   0.+0.5j  0.+0.5j  0.+0.j ]]

In [22]:
A(0, 0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.+0.j  0.-0.5j 0.-0.5j 0.+0.j ]
 [0.+0.5j 0.-0.2j 0.+0.j  0.-0.5j]
 [0.+0.5j 0.+0.j  0.-0.2j 0.-0.5j]
 [0.+0.j  0.+0.5j 0.+0.5j 0.+0.j ]]

In [23]:
I

NameError: name 'I' is not defined

In [24]:
#term1 = tensor(Lin.trans(), Lin)
#term2 = tensor(I, ((Lin.dag())*(Lin)))
#term3 = tensor(((Lin.trans())*(Lin.conj())), I)
#leftover = 1j*(0.1)*(term1 - 0.5*(term2 + term2))
def x_k(omega_1, Lin ):
    r"""Brief description of the function"""
    #H11 = H1(omega_1)
    #H2_i = H2()
    d = Lin.shape[0]
    I = identity(d)
    x_k = tensor(I, H2()) - tensor((H2().conj()), I) #+ leftover(Lin)
    return x_k


In [25]:
I

NameError: name 'I' is not defined

In [26]:
x_k(0.5, sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j 0.-1.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+1.j 0.+1.j 0.+0.j]]

In [27]:
def L(omega_1, xi, Lin, dt):
    #H = H1
    L = (-1j*A(omega_1, xi, Lin)*dt).expm()
    return L

In [28]:
L(0.5, 2, sigmaz(), 0.001)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 9.99996000e-01+0.00000000e+00j -1.99979435e-03-9.99865260e-07j
  -1.99979435e-03+9.99865260e-07j  3.99972768e-06+0.00000000e+00j]
 [ 1.99979435e-03+9.99865260e-07j  9.99795521e-01+9.99797187e-04j
  -3.99946104e-06+0.00000000e+00j -1.99979435e-03-9.99865260e-07j]
 [ 1.99979435e-03-9.99865260e-07j -3.99946104e-06+0.00000000e+00j
   9.99795521e-01-9.99797187e-04j -1.99979435e-03+9.99865260e-07j]
 [ 3.99972768e-06+0.00000000e+00j  1.99979435e-03+9.99865260e-07j
   1.99979435e-03-9.99865260e-07j  9.99996000e-01+0.00000000e+00j]]

In [29]:
def L_I(Ti):
    r"""Brief description of the function"""
    d = Ti.shape[0]
    I = identity(d)
    L_I = tensor(I, I)
    return L_I

In [30]:
L_I(sigmay())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

## parameters

### sub sub topic 1

In [31]:
# building the function to optimize (optimizee)
def L_vec(omega_1, xi_vec, Lin, dt):
    #xi_vec_size = 2#xi_vec.size # finding the size of xi
    L_vec = [L(omega_1, xi, Lin, dt) for xi in xi_vec] 
    # constructing L #[L(1.0), L(2.0)]
    
    return L_vec


In [32]:
def fidelity_calc(A, B):
    r"""Brief description of the function"""
    d1 = A.shape[0] # Assuming no rectangular shaped matrices
    d2 = B.shape[0] # Assuming no rectangular shaped matrices
    d = d1*d2
    first_part = (A - B).dag()
    second_part = (A - B)
    f_int = (first_part* second_part)
    f = f_int.tr()
    return f

In [33]:
def L_full_maker(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    xi_vec_size = xi_vec.size # finding the size of xi
    L_full = L_I(Ti) # Identity for the for loop of L
    L_v = L_vec(omega_1, xi_vec, Lin, dt) # calling L_vec
    for i in range(xi_vec_size): # generating L_full
        L_full = L_full*L_v[xi_vec_size - 1 - i]
    return L_full

In [34]:
def F(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    L_full = L_full_maker(Ti, omega_1, xi_vec, Lin, dt)
    T = T_maker(Ti)
    F = real(-fidelity_calc(T, L_full))   
    return F

In [35]:
fidelity_calc(sigmax(), sigmay())

4.0

In [36]:
fidelity_calc(sigmay(), sigmay())

0.0

In [37]:
xi_vec_test = array([1.0, 2.0])
xi_vec_test

array([1., 2.])

In [38]:
xi_vec_test.size

2

In [39]:
w_vec = [xi**2 for xi in xi_vec_test]
w_vec

[1.0, 4.0]

In [40]:
# F(Ti, omega_1, xi_vec, Lin, dt)
F(sigmax(), 0.5 , xi_vec_test, sigmaz(), 0.001)

-7.998400634493139

In [41]:
def L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt):
    N = xi_vec.size
    L_v = L_vec(omega_1, xi_vec, Lin, dt)
    
    inner_part = L_I(Ti)
    for i in range(N):
        if i == ( N - 1 - k ):
            inner_part = inner_part*x_k(omega_1, Lin )*L_v[k - 1]
        else:
            inner_part = inner_part*L_v[N - 1 - i]
    l_comma_k = inner_part
    return l_comma_k
    

In [42]:
#L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt)
L_comma_k_maker(sigmax(), 0.5 , xi_vec_test, 2, sigmaz(), 0.001)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 9.99991001e-01+0.00000000e+00j -2.99927960e-03-3.49898670e-06j
  -2.99927960e-03+3.49898670e-06j  8.99883703e-06+0.00000000e+00j]
 [ 2.99948056e-03+2.49939255e-06j  9.99589083e-01+1.99918650e-03j
  -8.99750347e-06+2.99899242e-09j -2.99948056e-03-2.49939255e-06j]
 [ 2.99948056e-03-2.49939255e-06j -8.99750347e-06-2.99899242e-09j
   9.99589083e-01-1.99918650e-03j -2.99948056e-03+2.49939255e-06j]
 [ 8.99883703e-06+0.00000000e+00j  2.99927960e-03+3.49898670e-06j
   2.99927960e-03-3.49898670e-06j  9.99991001e-01+0.00000000e+00j]]

In [43]:
def updater(Ti, omega_1, xi_vec, Lin, dt):
    r"""Brief description of the function"""
    xi_vec_size = xi_vec.size # finding the size of xi
    T = T_maker(Ti)
    L_full = L_full_maker(Ti, omega_1, xi_vec, Lin, dt)
    di = []
    for k in range(xi_vec_size):
        L_comma_k = L_comma_k_maker(Ti, omega_1, xi_vec, k, Lin, dt)
        differentiated = T - L_comma_k
        plain = T - L_full
        c = differentiated.dag()*plain
        d = plain.dag()*differentiated
        inside = c.tr() + d.tr()
        di.append(epsilon*inside)

    diff = array(di)
    xi_new_vec = xi_vec + diff
    return diff, xi_new_vec
    

In [44]:
#  updater(Ti, omega_1, xi_vec, Lin, dt)
updater(sigmax(), 0.5 , xi_vec_test, sigmaz(), 0.001)

NameError: name 'epsilon' is not defined

In [45]:
def terminator(max_iter, time_steps, Ti, omega_1, Lin, total_time):
    r"""Brief description of the function"""
    
    xi_initial =  1000*random_sample((time_steps,))
    dt = total_time/time_steps
    xi_diff, xi_new_vec = updater(Ti, omega_1, xi_initial, Lin, dt)
    
    #xi_diff = xi_new_vec - xi_initial
    for i in range(max_iter):
        if amax(xi_diff) < epsilon**2 :
            xi_final = xi_new_vec
            break
        else :
            xi_diff, xi_new_vec = updater(Ti, omega_1, xi_new_vec, Lin, dt)
            print(i)
            print(amax(xi_diff))
            
        
    xi_final = xi_new_vec    
    return xi_final

In [47]:
omega_1 = 0.5
total_time = 10*pi/omega_1
epsilon = 10**(-6)
max_iter = 100#50#20
time_steps = 20
dt = total_time/time_steps

In [48]:
Lin = sigmaz() # Lindbladian

In [49]:
Ti = sigmax() # Target unitary

In [50]:
# terminator(20, 20, Ti, omega_1, Lin, total_time)
xi_opt = terminator(max_iter, time_steps, Ti, omega_1, Lin, total_time)
xi_opt

0
(6.0000130357007835e-06+0j)
1
(6.000013037573336e-06+0j)
2
(6.000013039439732e-06+0j)
3
(6.0000130412999525e-06+0j)
4
(6.000013043156642e-06+0j)
5
(6.0000130450068965e-06+0j)
6
(6.000013046849188e-06+0j)
7
(6.0000130486845365e-06+0j)
8
(6.000013050519991e-06+0j)
9
(6.0000130523442965e-06+0j)
10
(6.000013054164159e-06+0j)
11
(6.0000130559794595e-06+0j)
12
(6.000013057787519e-06+0j)
13
(6.000013059593923e-06+0j)
14
(6.000013061388108e-06+0j)
15
(6.000013063178291e-06+0j)
16
(6.0000130649674295e-06+0j)
17
(6.000013066749133e-06+0j)
18
(6.000013068518872e-06+0j)
19
(6.000013070285615e-06+0j)
20
(6.000013072053951e-06+0j)
21
(6.000013073813411e-06+0j)
22
(6.000013075556849e-06+0j)
23
(6.000013077305499e-06+0j)
24
(6.0000130790464935e-06+0j)
25
(6.000013080779545e-06+0j)
26
(6.000013082503223e-06+0j)
27
(6.000013084226994e-06+0j)
28
(6.000013085944392e-06+0j)
29
(6.000013087657813e-06+0j)
30
(6.0000130893577466e-06+0j)
31
(6.000013091057294e-06+0j)
32
(6.000013092754296e-06+0j)
33
(6.00001

array([314.31405429+0.j, 156.48348865+0.j, 234.76318357+0.j,
       627.39627954+0.j, 817.31170092+0.j, 705.07224648+0.j,
       391.34386214+0.j,  26.95167144+0.j, 708.73079833+0.j,
       151.05307941+0.j, 538.8196842 +0.j, 901.11570264+0.j,
       799.17968458+0.j, 885.19737833+0.j, 579.58529298+0.j,
       422.75061263+0.j, 553.12980655+0.j, 845.71322167+0.j,
         4.58905801+0.j, 740.01983051+0.j])

In [51]:
F(Ti, omega_1, xi_opt, Lin, dt)

-3.000020046642919

In [52]:
max_iter

100

In [53]:
T = T_maker(Ti)
T

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

In [54]:
L_full_maker(Ti, omega_1, xi_opt, Lin, dt)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 4.99139330e-01+0.00000000e+00j  3.27396686e-04-2.19191563e-06j
   3.27396686e-04+2.19191563e-06j  5.00860670e-01+0.00000000e+00j]
 [-3.27083095e-04+1.19493524e-04j -8.60872673e-04+6.27657844e-06j
  -8.63968409e-04+5.54705049e-06j  3.27083095e-04-1.19493524e-04j]
 [-3.27083095e-04-1.19493524e-04j -8.63968409e-04-5.54705049e-06j
  -8.60872673e-04-6.27657844e-06j  3.27083095e-04+1.19493524e-04j]
 [ 5.00860670e-01+0.00000000e+00j -3.27396686e-04+2.19191563e-06j
  -3.27396686e-04-2.19191563e-06j  4.99139330e-01+0.00000000e+00j]]

In [55]:
hinton(L_full_maker(Ti, omega_1, xi_opt, Lin, dt))

(<Figure size 576x432 with 2 Axes>,
 <matplotlib.axes._subplots.AxesSubplot at 0x10f5fc320>)

In [12]:
1.31350478e-05 # 40

1.31350478e-05

In [13]:
1.31390107e-05 # 50

1.31390107e-05

In [14]:
α = 2

In [15]:
new_array = random_sample((4,3,))

NameError: name 'random_sample' is not defined

In [ ]:
new_array

In [ ]:
new_array.any()

In [ ]:
new_array[0] = 0


In [ ]:
new_array

In [ ]:
new_array.any()

In [ ]:
new_array.all()

In [ ]:
max(new_array)

In [ ]:
max(new_array, axis=0)

In [ ]:
from numpy import amax 

In [ ]:
amax(new_array)